[package]
name = "cell-smoother"
version = "0.1.0"
authors = ["Mika Viljanen <mika.viljanen@iki.fi>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.73"

[dev-dependencies]
wasm-bindgen-test = "0.3.23"
